apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels:
    app: {{ include "mongodb.fullname" . }}
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None  # Headless service for StatefulSet
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mongodb
      name: mongodb
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}
